# ARG VERSION=12.8
# FROM debian:$VERSION
ARG VERSION=41
FROM fedora:$VERSION

# Unless specified will inherit value as set at top of file.
ARG VERSION

ARG PROJECT_NAME=OH_NO_NAME_ME_PLEASE
ARG ZIG_VERSION=0.14.0

LABEL sh.jam.name="$PROJECT_NAME" \
	  sh.jam.summary="Image with $PROJECT_NAME project dependencies" \
	  sh.jam.box="true"

ENV JAM_PROJECT="$PROJECT_NAME"

# Getting a list of packages from a text file is cute but it's arguably pointless indirection here.
RUN dnf update -y && dnf install -y \
	git \
	ripgrep \
	rsync \
	htop \
	curl \
	minisign \
	man \
	which \
	lsof \
	acl \
	diffutils \
	just \
	\
	&& dnf clean all
	# zig-"$ZIG_VERSION" \
	# zig-doc-"$ZIG_VERSION" \
	# zig-libs-"$ZIG_VERSION" \
	# \
	# && dnf clean all

# TODO: Install zls (download from git and verify with minisign).

# -------------------------------------------- Namespace mapping.
# Without the following magic adduser namespace mapping will break horribly. If you do NOT want to use it one alternative is that the Containerfile must specify no USER at all, and when calling `run` on podman-machine as user `core` `--userns keep-id:uid=501` must be passed.

# UID for this account must match macOS UID that is running podman-machine (vm) as by default Podman will set up namespace mapping to said UID which is also (from macOS) default: 501.
ARG USERNAME=jammy
RUN adduser \
	--groups wheel \
	--home-dir /home/"$USERNAME" \
	--password '' \
	--shell /bin/bash \
	--uid 501 \
	--user-group \
	"$USERNAME"
# -------------------------------------------- /

# XXX: Temporary until zig 0.14.0 released and available in Fedora package repos.
# https://ziglang.org/builds/zig-linux-aarch64-0.14.0-dev.2851+b074fb7dd.tar.xz
# TODO: zls for zig 0.14.0-dev also
# COPY .jam/zig-linux-aarch64-0.14.0-dev.2851+b074fb7dd.tar.xz /tmp/zig.tar.xz
# COPY .jam/zig-linux-aarch64-0.14.0-dev.3020+c104e8644.tar.xz /tmp/zig.tar.xz
# COPY .jam/zig-linux-aarch64-0.14.0-dev.3028+cdc9d65b0.tar.xz /tmp/zig.tar.xz
COPY .jam/zig-linux-aarch64-0.14.0.tar.xz /tmp/zig.tar.xz

RUN chown 501:1000 /tmp/zig.tar.xz
USER $USERNAME
RUN mkdir -p /home/"$USERNAME"/bin
RUN tar -xf /tmp/zig.tar.xz -C /home/jammy/bin --strip-components=1
RUN touch /home/"$USERNAME"/.tramp_history
RUN rm -f /tmp/zig.tar.xz

WORKDIR /home/$USERNAME/project

USER $USERNAME

# CMD ["/bin/bash", "-l"]

# ls -lan
# ls -la@
# podman top -l capeff
# podman top -l user uid huser group hgroups
